language: node_js

node_js:
  - "stable"

services:
  - postgresql

before_script:
  - psql -c 'create database test_db;' -U postgres

install:
  - yarn install

script:
  - yarn migrate
  - yarn test
